### ISSUE TITLE
Error using $profile->getMoreMedia() | Syntax Error on AbstractDataFeed.php:61

### ISSUE THREAD

**Issue by lucasborgesbr** [pgrimaud/instagram-user-feed#294]
**Version(s) affected**: 6.15.0

**Description**  
Having issues with getMoreMedia() function

**Fatal error:** Uncaught Instagram\Exception\InstagramFetchException: Syntax error in (...)\pgrimaud\instagram-user-feed\src\Instagram\Transport\AbstractDataFeed.php:61 Stack trace: #0 (...)\pgrimaud\instagram-user-feed\src\Instagram\Transport\JsonMediasDataFeed.php(34): Instagram\Transport\AbstractDataFeed->fetchJsonDataFeed('https://www.ins...') #1 (...)\pgrimaud\instagram-user-feed\src\Instagram\Api.php(157): Instagram\Transport\JsonMediasDataFeed->fetchData(Object(Instagram\Model\Profile), 12) #2 C:\xampp\htdocs\comidasdesobradinho\service\cronJobs\searchNewPost.php(46): Instagram\Api->getMoreMedias(Object(Instagram\Model\Profile)) #3 {main} thrown in (...)\pgrimaud\instagram-user-feed\src\Instagram\Transport\AbstractDataFeed.php on line 61

**Comment by lucasborgesbr** [comment]
The issue had to do with cahce folder missplaced on my project. Thanks!
