### ISSUE TITLE
Please wait a few minutes before you try again

### ISSUE THREAD

**Issue by omeshgrover** [pgrimaud/instagram-user-feed#375]
**Version(s) affected**: x.y.z

**Description**  
A clear and concise description of the problem.
I am getting this Error as response while working with 2 functions getHashtag() and getProfileById(). Here I am getting all owner ids related to hashtag and loop it to get particular profile using the same owner id.

Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://www.instagram.com/graphql/query/?query_hash=c9100bf9110dd6361671f113dd02e7d6&variables=%7B%22user_id%22:40750166343,%22include_chaining%22:false,%22include_reel%22:true,%22include_suggested_users%22:false,%22include_logged_out_extras%22:false,%22include_highlight_reels%22:false,%22include_related_profiles%22:false%7D` resulted in a `401 Unauthorized` response: {"message":"Please wait a few minutes before you try again.","require_login":true,"status":"fail"} in C:\OSPanel\domains\instagramfeeds.local\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:113 Stack trace: #0 C:\OSPanel\domains\instagramfeeds.local\vendor\guzzlehttp\guzzle\src\Middleware.php(72): GuzzleHttp\Exception\RequestException::create() #1 C:\OSPanel\domains\instagramfeeds.local\vendor\guzzlehttp\promises\src\Promise.php(209): GuzzleHttp\Middleware::GuzzleHttp\{closure}() #2 C:\OSPanel\domains\instagramfeeds.local\vendor\guzzlehttp\promises\src\Promise.php(158): GuzzleHttp\Promise\Promise::callHandler() #3 C:\OSPanel\domains\instagramfeeds.local\vendor\guzzlehttp\promises\src\TaskQueue.php(52): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #4 C:\OSPanel\domains\instagramfeeds.local\vendor\guzzlehttp\promises\src\Promise.php(251): GuzzleHttp\Promise\TaskQueue->run() #5 C:\OSPanel\domains\instagramfeeds.local\vendor\guzzlehttp\promises\src\Promise.php(227): GuzzleHttp\Promise\Promise->invokeWaitFn() #6 C:\OSPanel\domains\instagramfeeds.local\vendor\guzzlehttp\promises\src\Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending() #7 C:\OSPanel\domains\instagramfeeds.local\vendor\guzzlehttp\promises\src\Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList() #8 C:\OSPanel\domains\instagramfeeds.local\vendor\guzzlehttp\promises\src\Promise.php(69): GuzzleHttp\Promise\Promise->waitIfPending() #9 C:\OSPanel\domains\instagramfeeds.local\vendor\guzzlehttp\guzzle\src\Client.php(189): GuzzleHttp\Promise\Promise->wait() #10 C:\OSPanel\domains\instagramfeeds.local\vendor\pgrimaud\instagram-user-feed\src\Instagram\Transport\AbstractDataFeed.php(56): GuzzleHttp\Client->request() #11 C:\OSPanel\domains\instagramfeeds.local\vendor\pgrimaud\instagram-user-feed\src\Instagram\Transport\JsonProfileDataFeed.php(33): Instagram\Transport\AbstractDataFeed->fetchJsonDataFeed() #12 C:\OSPanel\domains\instagramfeeds.local\vendor\pgrimaud\instagram-user-feed\src\Instagram\Api.php(446): Instagram\Transport\JsonProfileDataFeed->fetchData() #13 C:\OSPanel\domains\instagramfeeds.local\index2.php(12): Instagram\Api->getProfileById() #14 {main} thrown in C:\OSPanel\domains\instagramfeeds.local\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 113

**How to reproduce**  
Code and/or config needed to reproduce the problem.

<?php
require __DIR__ . '/vendor/autoload.php';

use Instagram\Api;
use Symfony\Component\Cache\Adapter\FilesystemAdapter;

$cachePool = new FilesystemAdapter('Instagram', 0, __DIR__ . '/../cache');

try {
    $api = new Api($cachePool);
    $api->login('USERNAME', 'PASSWORD'); // mandatory

    $duplicate = [];
    $res = $api->getHashtag('dog');
    foreach($res->getMedias() as $v) {
        if(in_array($v->getOwnerId(), $duplicate)) {
            continue;
        }

        $profile = $api->getProfileById($v->getOwnerId());
        echo "<tr>";
        echo "<td>".$profile->getUsername()."</td>";
        echo "<td>".$profile->getFullName()."</td>";
        echo "<td>".$profile->getFollowers()."</td>";
        echo "<td>".$profile->getBiography()."</td>";
        echo "</tr>";

        $duplicate[] = $v->getOwnerId();
    }
} catch(\exception $e) {
    echo "Error: ".$e->getMessage();
}
?>

**Possible Solution**  
Optional: only if you have suggestions on a fix/reason for the bug

**Additional context**  
Optional: any other context about the problem: log messages, screenshots, etc.

**Comment by omeshgrover** [comment]
*Note*  I created a new account for this Script and I am able to login in Instagram Account with same USERNAME / PASSWORD without any notifications or issues.
I was able to fetch records from IG but while working I faced this issue and now more than 12 hours the issues is as it.

**Comment by thierrydrc** [comment]
Same :(
