### ISSUE TITLE
Undefined property: stdClass::$ProfilePage in HtmlProfileDataFeed.php on line 47

### ISSUE THREAD

**Issue by vietel** [pgrimaud/instagram-user-feed#77]
Hello, 

I have added your project to my WP plugin.

After adding, it works very well.

But after a short time, it displays an error below:

Hope you have any advice for me.

Thank you

===================
```
Notice: Undefined property: stdClass::$ProfilePage in /var/www/html/wp-content/plugins/my-instagram-app/lib/instagram-user-feed/vendor/pgrimaud/instagram-user-feed/src/Instagram/Transport/HtmlProfileDataFeed.php on line 47

Notice: Trying to get property 'graphql' of non-object in /var/www/html/wp-content/plugins/my-instagram-app/lib/instagram-user-feed/vendor/pgrimaud/instagram-user-feed/src/Instagram/Transport/HtmlProfileDataFeed.php on line 47

Notice: Trying to get property 'user' of non-object in /var/www/html/wp-content/plugins/my-instagram-app/lib/instagram-user-feed/vendor/pgrimaud/instagram-user-feed/src/Instagram/Transport/HtmlProfileDataFeed.php on line 47

Fatal error: Uncaught TypeError: Return value of Instagram\Transport\HtmlProfileDataFeed::fetchData() must be an instance of stdClass, null returned in /var/www/html/wp-content/plugins/my-instagram-app/lib/instagram-user-feed/vendor/pgrimaud/instagram-user-feed/src/Instagram/Transport/HtmlProfileDataFeed.php:47 Stack trace: #0 /var/www/html/wp-content/plugins/my-instagram-app/lib/instagram-user-feed/vendor/pgrimaud/instagram-user-feed/src/Instagram/Api.php(101): Instagram\Transport\HtmlProfileDataFeed->fetchData('nasa') #1 /var/www/html/wp-content/plugins/my-instagram-app/templates/frontend/followers/step-2.php(47): Instagram\Api->getProfile('nasa') #2 /var/www/html/wp-content/plugins/my-instagram-app/includes/frontend/router.php(68): include_once('/var/www/html/w...') #3 /var/www/html/wp-includes/class-wp-hook.php(287): IGB_Instagram_Purchases_Router->step('<p>I know you a...') #4 /var/www/html/wp-includes/plugin.php(206): WP_Hook->apply_filters('<p>I know you a...', Array) #5 /var/www/html/wp in /var/www/html/wp-content/plugins/my-instagram-app/lib/instagram-user-feed/vendor/pgrimaud/instagram-user-feed/src/Instagram/Transport/HtmlProfileDataFeed.php on line 47
```
===================

print_r($data); (in HtmlProfileDataFeed.php)

```
stdClass Object
(
    [config] => stdClass Object
        (
            [csrf_token] => Ok5XBylhJegjeDzJefnI0IVkti0TKw8f
            [viewer] => 
            [viewerId] => 
        )

    [country_code] => VN
    [language_code] => en
    [locale] => en_US
    [entry_data] => stdClass Object
        (
            [LoginAndSignupPage] => Array
                (
                    [0] => stdClass Object
                        (
                            [captcha] => stdClass Object
                                (
                                    [enabled] => 
                                    [key] => 
                                )

                            [gdpr_required] => 
                            [tos_version] => row
                            [username_hint] => 
                        )

                )

        )

    [hostname] => www.instagram.com
    [is_whitelisted_crawl_bot] => 
    [deployment_stage] => c2
    [platform] => web
    [nonce] => EM5eSFYu664OJVP4sY5Vjg==
    [mid_pct] => 38.52267
    [zero_data] => stdClass Object
        (
        )

    [cache_schema_version] => 3
    [server_checks] => stdClass Object
        (
        )

    [knobx] => stdClass Object
        (
            [17] => 
            [20] => 1
            [22] => 1
            [23] => 1
            [24] => 1
            [25] => 1
            [26] => 1
            [27] => 1
            [28] => 1
            [29] => 1
            [30] => 1
            [4] => 
        )

    [to_cache] => stdClass Object
        (
            [gatekeepers] => stdClass Object
                (
                    [10] => 
                    [100] => 
                    [101] => 1
                    [102] => 1
                    [103] => 1
                    [104] => 1
                    [105] => 1
                    [106] => 1
                    [107] => 
                    [108] => 1
                    [109] => 
                    [11] => 
                    [111] => 
                    [112] => 
                    [113] => 1
                    [114] => 1
                    [116] => 1
                    [117] => 1
                    [119] => 
                    [12] => 
                    [120] => 
                    [123] => 
                    [13] => 1
                    [14] => 1
                    [15] => 1
                    [16] => 1
                    [18] => 1
                    [19] => 
                    [23] => 
                    [24] => 
                    [26] => 1
                    [27] => 
                    [28] => 
                    [29] => 1
                    [31] => 
                    [32] => 1
                    [34] => 
                    [35] => 
                    [38] => 1
                    [4] => 1
                    [40] => 1
                    [41] => 
                    [43] => 1
                    [5] => 
                    [59] => 1
                    [6] => 
                    [61] => 
                    [62] => 
                    [63] => 
                    [64] => 
                    [65] => 
                    [67] => 1
                    [68] => 
                    [69] => 1
                    [7] => 
                    [71] => 
                    [72] => 1
                    [73] => 
                    [74] => 
                    [75] => 1
                    [77] => 1
                    [78] => 1
                    [79] => 
                    [8] => 
                    [81] => 
                    [82] => 1
                    [84] => 
                    [86] => 
                    [88] => 1
                    [9] => 
                    [91] => 
                    [95] => 1
                    [97] => 
                    [99] => 
                )

            [qe] => stdClass Object
                (
                    [app_upsell] => stdClass Object
                        (
                            [g] => 
                            [p] => stdClass Object
                                (
                                )

                        )

                    [igl_app_upsell] => stdClass Object
                        (
                            [g] => 
                            [p] => stdClass Object
                                (
                                )

                        )

                    [notif] => stdClass Object
                        (
                            [g] => 
                            [p] => stdClass Object
                                (
                                )

                        )

                    [onetaplogin] => stdClass Object
                        (
                            [g] => 
                            [p] => stdClass Object
                                (
                                )

                        )

                    [felix_clear_fb_cookie] => stdClass Object
                        (
                            [g] => 
                            [p] => stdClass Object
                                (
                                )

                        )

                    [felix_creation_duration_limits] => stdClass Object
                        (
                            [g] => 
                            [p] => stdClass Object
                                (
                                )

                        )

                    [felix_creation_fb_crossposting] => stdClass Object
                        (
                            [g] => 
                            [p] => stdClass Object
                                (
                                )

                        )

                    [felix_creation_fb_crossposting_v2] => stdClass Object
                        (
                            [g] => 
                            [p] => stdClass Object
                                (
                                )

                        )

                    [felix_creation_validation] => stdClass Object
                        (
                            [g] => 
                            [p] => stdClass Object
                                (
                                )

                        )

                    [post_options] => stdClass Object
                        (
                            [g] => 
                            [p] => stdClass Object
                                (
                                )

                        )

                    [sticker_tray] => stdClass Object
                        (
                            [g] => 
                            [p] => stdClass Object
                                (
                                )

                        )

                    [web_sentry] => stdClass Object
                        (
                            [g] => 
                            [p] => stdClass Object
                                (
                                )

                        )

                    [0] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [9] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [100] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 1
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [101] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 
                                    [1] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [102] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 1
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [103] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 
                                    [1] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [104] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 1
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [108] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 
                                    [1] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [109] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [110] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [111] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 
                                    [1] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [112] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [113] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 1
                                    [1] => 
                                    [2] => 1
                                    [3] => 1
                                    [4] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [114] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [1] => 1
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [115] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 1
                                    [1] => 1
                                    [2] => 1
                                    [3] => 1
                                )

                            [l] => stdClass Object
                                (
                                    [0] => 1
                                    [1] => 1
                                    [2] => 1
                                    [3] => 1
                                )

                            [qex] => 1
                        )

                    [116] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 1
                                )

                            [l] => stdClass Object
                                (
                                    [0] => 1
                                )

                            [qex] => 1
                        )

                    [117] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 1
                                )

                            [l] => stdClass Object
                                (
                                    [0] => 1
                                )

                            [qex] => 1
                        )

                    [118] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [119] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [12] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 5
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [120] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 1
                                )

                            [l] => stdClass Object
                                (
                                    [0] => 1
                                )

                            [qex] => 1
                        )

                    [121] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 
                                )

                            [l] => stdClass Object
                                (
                                    [0] => 1
                                )

                            [qex] => 1
                        )

                    [122] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 1
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [123] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 
                                    [1] => 
                                )

                            [l] => stdClass Object
                                (
                                    [0] => 1
                                )

                            [qex] => 1
                        )

                    [124] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 
                                    [1] => 
                                    [2] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [125] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 1
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [13] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 1
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [16] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [21] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [2] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [22] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [1] => 
                                    [10] => 0
                                    [11] => 15
                                    [12] => 3
                                    [13] => 
                                    [2] => 8
                                    [3] => 0.85
                                    [4] => 0.95
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [23] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 
                                    [1] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [25] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [26] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [28] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [29] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [31] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [33] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [34] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [36] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 1
                                    [1] => 1
                                    [2] => 
                                    [3] => 
                                    [4] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [37] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [39] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 
                                    [14] => 
                                    [8] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [41] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [3] => 1
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [42] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 1
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [43] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 
                                    [1] => 
                                    [2] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [44] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [1] => inside_media
                                    [2] => 0.2
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [45] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [13] => 
                                    [17] => 0
                                    [26] => control
                                    [32] => 
                                    [33] => 
                                    [35] => 
                                    [36] => control
                                    [37] => 
                                    [38] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [46] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [47] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 1
                                    [1] => 1
                                    [10] => 
                                    [11] => 
                                    [2] => 
                                    [3] => 
                                    [4] => 
                                    [6] => 
                                    [8] => 
                                    [9] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [49] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [50] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [54] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [55] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [58] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 0
                                    [1] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [59] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 1
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [62] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [65] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [66] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [67] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 1
                                    [1] => 1
                                    [2] => 1
                                    [3] => 1
                                    [4] => 
                                    [5] => 1
                                    [7] => 
                                )

                            [l] => stdClass Object
                                (
                                    [4] => 1
                                    [5] => 1
                                )

                            [qex] => 1
                        )

                    [68] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [69] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 1
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [71] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [1] => ^/explore/.*|^/accounts/activity/$
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [72] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 
                                    [1] => 
                                    [2] => 
                                    [3] => 
                                    [4] => 
                                )

                            [l] => stdClass Object
                                (
                                    [1] => 1
                                    [2] => 1
                                )

                            [qex] => 1
                        )

                    [73] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [74] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [1] => 1
                                    [12] => 
                                    [2] => 
                                    [3] => 1
                                    [4] => 
                                    [7] => 
                                    [9] => 1
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [75] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 1
                                    [1] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [77] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [1] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [78] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 1
                                    [1] => 1
                                    [2] => 
                                    [3] => 
                                    [5] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [80] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [3] => 1
                                    [4] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [84] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 1
                                    [1] => 1
                                    [2] => 1
                                    [3] => 1
                                    [4] => 1
                                    [5] => 1
                                    [6] => 
                                    [8] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [85] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 
                                    [1] => Pictures and Videos
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [87] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 1
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [89] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [92] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 36
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [93] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 1
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [95] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 
                                    [1] => 
                                )

                            [l] => stdClass Object
                                (
                                    [1] => 1
                                )

                            [qex] => 1
                        )

                    [96] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 1
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [97] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [98] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [1] => 
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                    [99] => stdClass Object
                        (
                            [p] => stdClass Object
                                (
                                    [0] => 1
                                    [1] => 1
                                    [2] => 1
                                    [3] => 10
                                    [4] => 10000000
                                    [5] => 30000
                                )

                            [l] => stdClass Object
                                (
                                )

                            [qex] => 1
                        )

                )

            [probably_has_app] => 
            [cb] => 
        )

    [device_id] => 6D6B8B3C-5A20-496A-907F-49C4C94BBBD9
    [encryption] => stdClass Object
        (
            [key_id] => 230
            [public_key] => 1beeb8288a47f8821b4385c8c773481fa4577f6647a668181f59c9856391b114
            [version] => 10
        )

    [is_dev] => 
    [rollout_hash] => 5fb9742e2e7e
    [bundle_variant] => es6
    [frontend_env] => prod
)
```

**Comment by kumamidori** [comment]
I am not sure if this is the same incident as mentioned above.
Since around 29 May 2020, I have not been able to retrieve data when I accessed 'continuously' while using the library.
Previously I could get data while using the same code without problem.

I doubt that the server blocks my IP address.
I guess that the operation policy of Instagram has been changed.

When I am blocked, empty data are returned.
In other words, the status code is 200, but data cannot be retrieved.

Sometimes I can succeed once or twice as usual, but from around the third time I am always blocked.
Even if I change my IP address and user agent by using a proxy server, I am always blocked.
The situation does not change on the next day.

The result looks like this:

```
PHP Notice:  Undefined property: stdClass::$ProfilePage 
in /{path_to_project}/vendor/pgrimaud/instagram-user-feed/src/Instagram/Transport/HtmlTransportFeed.php on line 60
```

**Comment by rbait** [comment]
Instagram seems to have made a change in their frontend. To fix it, change HtmlProfileDataFeed fetchData to the following:

```
    public function fetchData(string $userName): \StdClass
    {
        $endpoint = InstagramHelper::URL_BASE . $userName . '/';

        $headers = [
            'headers' => [
                'user-agent' => UserAgentHelper::AGENT_DEFAULT,
            ],
            'cookies' => $this->session->getCookies()
        ];

        $res = $this->client->request('GET', $endpoint, $headers);

        $html = (string)$res->getBody();

        preg_match('/<script type="text\/javascript">window\._sharedData\s?=(.+);<\/script>/', $html, $matches);

        if (!isset($matches[1])) {
            throw new InstagramFetchException('Unable to extract JSON data');
        }

        $data = json_decode($matches[1]);

        if ($data === null) {
            throw new InstagramFetchException(json_last_error_msg());
        }

        if (!empty($data->entry_data->ProfilePage[0]->graphql)) {
            return $data->entry_data->ProfilePage[0]->graphql->user;
        }

        preg_match('/<script type="text\/javascript">window\.__additionalDataLoaded\([^,]*,(.+)\);<\/script>/', $html, $matches);

        if (!isset($matches[1])) {
            throw new InstagramFetchException('Unable to extract JSON data');
        }

        $data = json_decode($matches[1]);

        return $data->graphql->user;
    }
```

I kept the old method in there for backwards compatibility just to be sure

**Comment by pgrimaud** [comment]
I released a new version 6.2.3 with @bytehead fix 🎉
But I can't reproduce this bug on my side.

Someone could fetch the code source of the page when `_sharedData` is empty and `__additionalDataLoaded` contains user data? @rbait @bytehead  or @vietel (https://github.com/pgrimaud/instagram-user-feed/commit/7e6a674fc5e09547173539faca3f54a947511d95)

Thanks

**Comment by bytehead** [comment]
Thank you @pgrimaud! I'll check if I can provide you the source for the missing tests.

**Comment by bytehead** [comment]
This is the result of a `print_r($data)` after this line:
https://github.com/pgrimaud/instagram-user-feed/blob/11600f181a7383eb3fdc631765e3d33b0f18aca4/src/Instagram/Transport/HtmlProfileDataFeed.php#L40

https://gist.github.com/bytehead/8339ce354e5d0e8b3cc61b7757f11ad8

**Comment by bytehead** [comment]
Sorry, did misread you comment. Here's the page source:
https://gist.github.com/bytehead/64bf875f373c1b990a7989fd5ae61108

`_sharedData` is not really empty, but doesn't contain the useful data.

**Comment by bytehead** [comment]
PS: great to have you back, hope all went well for you! 🎉

**Comment by pgrimaud** [comment]
> PS: great to have you back, hope all went well for you! 🎉

The worst is behind me. 🦾 

Thanks for the PR!
